export const allBill = {
    importBillData: [
      {
        date: "2022/9/16",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "5748.77",
            rate: "1684.99",
            kg: "7.33",
            pcs: 14,
            discount: 23,
          },
          {
            id: 2,
            name: "Peeler",
            price: "7447.21",
            rate: "3743.13",
            kg: null,
            pcs: 24,
            discount: 19,
          },
          {
            id: 3,
            name: "Cutting Board",
            price: "8940.97",
            rate: "4584.39",
            kg: null,
            pcs: 29,
            discount: 13,
          },
        ],
      },
      {
        date: "2023/7/4",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "8484.67",
            rate: "4495.34",
            kg: null,
            pcs: 2,
            discount: 26,
          },
          {
            id: 2,
            name: "Peeler",
            price: "6354.26",
            rate: "2874.31",
            kg: null,
            pcs: 19,
            discount: 14,
          },
        ],
      },
      {
        date: "2021/9/22",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "9219.24",
            rate: "3137.87",
            kg: null,
            pcs: 24,
            discount: 17,
          },
          {
            id: 2,
            name: "Colander",
            price: "9910.03",
            rate: "2574.35",
            kg: null,
            pcs: 22,
            discount: 19,
          },
        ],
      },
      {
        date: "2020/12/27",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "5425.62",
            rate: "4972.00",
            kg: "1.75",
            pcs: 30,
            discount: 20,
          },
          {
            id: 2,
            name: "Blender",
            price: "8217.79",
            rate: "3988.57",
            kg: "9.34",
            pcs: 10,
            discount: 28,
          },
          {
            id: 3,
            name: "Peeler",
            price: "9878.41",
            rate: "1770.41",
            kg: null,
            pcs: 4,
            discount: 24,
          },
          {
            id: 4,
            name: "Colander",
            price: "5609.52",
            rate: "3942.42",
            kg: "2.18",
            pcs: 23,
            discount: 14,
          },
          {
            id: 5,
            name: "Cutting Board",
            price: "5479.66",
            rate: "2038.09",
            kg: "0.65",
            pcs: 6,
            discount: 19,
          },
        ],
      },
      {
        date: "2023/3/28",
        bill: [
          {
            id: 1,
            name: "Whisk",
            price: "9434.13",
            rate: "3578.68",
            kg: null,
            pcs: 20,
            discount: 29,
          },
          {
            id: 2,
            name: "Cutting Board",
            price: "9028.39",
            rate: "2915.94",
            kg: null,
            pcs: 21,
            discount: 20,
          },
          {
            id: 3,
            name: "Peeler",
            price: "9532.06",
            rate: "2386.84",
            kg: null,
            pcs: 21,
            discount: 28,
          },
          {
            id: 4,
            name: "Frying Pan",
            price: "9227.88",
            rate: "2296.86",
            kg: null,
            pcs: 29,
            discount: 25,
          },
          {
            id: 5,
            name: "Blender",
            price: "9776.92",
            rate: "1700.60",
            kg: "2.41",
            pcs: 26,
            discount: 28,
          },
        ],
      },
      {
        date: "2022/8/25",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "6416.70",
            rate: "1623.20",
            kg: null,
            pcs: 3,
            discount: 11,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "5355.94",
            rate: "1125.29",
            kg: null,
            pcs: 15,
            discount: 15,
          },
          {
            id: 3,
            name: "Whisk",
            price: "5558.74",
            rate: "2398.40",
            kg: null,
            pcs: 3,
            discount: 23,
          },
        ],
      },
      {
        date: "2023/7/9",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "9875.36",
            rate: "4757.39",
            kg: "4.24",
            pcs: 30,
            discount: 17,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "9535.17",
            rate: "3071.31",
            kg: null,
            pcs: 11,
            discount: 20,
          },
          {
            id: 3,
            name: "Blender",
            price: "7846.28",
            rate: "2704.09",
            kg: "7.94",
            pcs: 24,
            discount: 14,
          },
        ],
      },
      {
        date: "2022/1/22",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "8711.72",
            rate: "2010.10",
            kg: "1.31",
            pcs: 5,
            discount: 14,
          },
          {
            id: 2,
            name: "Spatula",
            price: "6232.95",
            rate: "4299.58",
            kg: "1.63",
            pcs: 26,
            discount: 16,
          },
          {
            id: 3,
            name: "Blender",
            price: "8850.29",
            rate: "4266.95",
            kg: null,
            pcs: 6,
            discount: 28,
          },
        ],
      },
      {
        date: "2021/4/12",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "6571.90",
            rate: "2435.70",
            kg: "5.68",
            pcs: 7,
            discount: 23,
          },
          {
            id: 2,
            name: "Cutting Board",
            price: "5680.27",
            rate: "3724.30",
            kg: null,
            pcs: 3,
            discount: 27,
          },
          {
            id: 3,
            name: "Frying Pan",
            price: "5253.70",
            rate: "4656.53",
            kg: null,
            pcs: 22,
            discount: 12,
          },
          {
            id: 4,
            name: "Whisk",
            price: "9668.03",
            rate: "4116.17",
            kg: "1.81",
            pcs: 4,
            discount: 18,
          },
          {
            id: 5,
            name: "Knife",
            price: "6656.60",
            rate: "4436.18",
            kg: "3.97",
            pcs: 15,
            discount: 17,
          },
        ],
      },
      {
        date: "2020/9/7",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "8960.64",
            rate: "3557.70",
            kg: null,
            pcs: 22,
            discount: 25,
          },
        ],
      },
      {
        date: "2020/11/1",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "9021.99",
            rate: "2156.54",
            kg: "3.69",
            pcs: 13,
            discount: 14,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "6228.05",
            rate: "3070.49",
            kg: null,
            pcs: 5,
            discount: 29,
          },
          {
            id: 3,
            name: "Spatula",
            price: "5904.89",
            rate: "2192.10",
            kg: null,
            pcs: 11,
            discount: 15,
          },
        ],
      },
      {
        date: "2022/7/6",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "8983.09",
            rate: "3044.75",
            kg: null,
            pcs: 21,
            discount: 15,
          },
          {
            id: 2,
            name: "Whisk",
            price: "6937.17",
            rate: "4033.08",
            kg: "6.11",
            pcs: 3,
            discount: 19,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "8432.71",
            rate: "2503.41",
            kg: null,
            pcs: 18,
            discount: 21,
          },
        ],
      },
      {
        date: "2021/9/8",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "6734.50",
            rate: "4256.77",
            kg: "1.24",
            pcs: 23,
            discount: 12,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "9941.53",
            rate: "2882.45",
            kg: "7.15",
            pcs: 18,
            discount: 14,
          },
          {
            id: 3,
            name: "Knife",
            price: "6192.70",
            rate: "3959.18",
            kg: null,
            pcs: 23,
            discount: 19,
          },
        ],
      },
      {
        date: "2021/5/6",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "6400.33",
            rate: "2328.75",
            kg: null,
            pcs: 24,
            discount: 18,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "8808.40",
            rate: "4654.65",
            kg: null,
            pcs: 2,
            discount: 19,
          },
          {
            id: 3,
            name: "Colander",
            price: "5270.61",
            rate: "3401.73",
            kg: "9.82",
            pcs: 25,
            discount: 18,
          },
        ],
      },
      {
        date: "2020/8/19",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "6512.22",
            rate: "3739.03",
            kg: null,
            pcs: 12,
            discount: 14,
          },
          {
            id: 2,
            name: "Cutting Board",
            price: "9054.69",
            rate: "1415.39",
            kg: null,
            pcs: 12,
            discount: 22,
          },
        ],
      },
      {
        date: "2022/1/29",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "9720.28",
            rate: "4287.49",
            kg: null,
            pcs: 5,
            discount: 10,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "8829.24",
            rate: "3148.41",
            kg: "8.82",
            pcs: 20,
            discount: 20,
          },
          {
            id: 3,
            name: "Knife",
            price: "6982.72",
            rate: "3758.32",
            kg: null,
            pcs: 28,
            discount: 21,
          },
          {
            id: 4,
            name: "Measuring Cup",
            price: "6659.98",
            rate: "3207.25",
            kg: "4.49",
            pcs: 13,
            discount: 27,
          },
        ],
      },
      {
        date: "2020/9/25",
        bill: [
          {
            id: 1,
            name: "Whisk",
            price: "7143.41",
            rate: "3545.35",
            kg: null,
            pcs: 27,
            discount: 16,
          },
        ],
      },
      {
        date: "2023/6/25",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "8458.30",
            rate: "3677.00",
            kg: "0.55",
            pcs: 17,
            discount: 28,
          },
          {
            id: 2,
            name: "Spatula",
            price: "8193.37",
            rate: "2035.20",
            kg: "5.99",
            pcs: 12,
            discount: 17,
          },
          {
            id: 3,
            name: "Knife",
            price: "8311.09",
            rate: "1793.60",
            kg: null,
            pcs: 18,
            discount: 24,
          },
        ],
      },
      {
        date: "2022/12/30",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "7359.34",
            rate: "4724.74",
            kg: null,
            pcs: 23,
            discount: 19,
          },
          {
            id: 2,
            name: "Colander",
            price: "9707.07",
            rate: "2986.01",
            kg: null,
            pcs: 16,
            discount: 27,
          },
          {
            id: 3,
            name: "Whisk",
            price: "8282.71",
            rate: "4017.26",
            kg: null,
            pcs: 17,
            discount: 23,
          },
          {
            id: 4,
            name: "Spatula",
            price: "6572.72",
            rate: "1445.78",
            kg: null,
            pcs: 24,
            discount: 24,
          },
          {
            id: 5,
            name: "Cutting Board",
            price: "5470.52",
            rate: "2898.66",
            kg: "8.49",
            pcs: 19,
            discount: 10,
          },
        ],
      },
      {
        date: "2020/6/27",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "5864.74",
            rate: "1969.21",
            kg: "5.08",
            pcs: 25,
            discount: 26,
          },
          {
            id: 2,
            name: "Cutting Board",
            price: "9404.41",
            rate: "4473.75",
            kg: "2.55",
            pcs: 21,
            discount: 29,
          },
        ],
      },
      {
        date: "2020/10/30",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "9308.63",
            rate: "1802.45",
            kg: "3.06",
            pcs: 7,
            discount: 26,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "9564.41",
            rate: "1254.57",
            kg: "5.73",
            pcs: 14,
            discount: 25,
          },
          {
            id: 3,
            name: "Blender",
            price: "8862.64",
            rate: "1161.48",
            kg: null,
            pcs: 28,
            discount: 19,
          },
          {
            id: 4,
            name: "Blender",
            price: "9129.29",
            rate: "2233.57",
            kg: "6.94",
            pcs: 8,
            discount: 28,
          },
        ],
      },
      {
        date: "2022/2/4",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "5814.57",
            rate: "4737.91",
            kg: "4.87",
            pcs: 23,
            discount: 12,
          },
        ],
      },
      {
        date: "2021/7/25",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "5489.18",
            rate: "1243.57",
            kg: null,
            pcs: 15,
            discount: 21,
          },
          {
            id: 2,
            name: "Peeler",
            price: "9926.43",
            rate: "2475.96",
            kg: "4.39",
            pcs: 18,
            discount: 16,
          },
          {
            id: 3,
            name: "Spatula",
            price: "7581.40",
            rate: "1147.88",
            kg: "7.25",
            pcs: 3,
            discount: 26,
          },
          {
            id: 4,
            name: "Peeler",
            price: "8867.73",
            rate: "2912.50",
            kg: null,
            pcs: 5,
            discount: 14,
          },
        ],
      },
      {
        date: "2023/8/11",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "7908.18",
            rate: "3212.24",
            kg: "8.10",
            pcs: 23,
            discount: 20,
          },
          {
            id: 2,
            name: "Blender",
            price: "9494.48",
            rate: "3900.81",
            kg: null,
            pcs: 13,
            discount: 17,
          },
          {
            id: 3,
            name: "Measuring Cup",
            price: "9433.53",
            rate: "1357.63",
            kg: "1.90",
            pcs: 26,
            discount: 26,
          },
        ],
      },
      {
        date: "2022/9/3",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "7944.50",
            rate: "1062.68",
            kg: null,
            pcs: 15,
            discount: 22,
          },
          {
            id: 2,
            name: "Blender",
            price: "9623.70",
            rate: "4104.44",
            kg: "5.86",
            pcs: 19,
            discount: 15,
          },
          {
            id: 3,
            name: "Measuring Cup",
            price: "8045.09",
            rate: "3201.35",
            kg: "6.67",
            pcs: 12,
            discount: 23,
          },
          {
            id: 4,
            name: "Mixing Bowl",
            price: "6801.66",
            rate: "3131.11",
            kg: null,
            pcs: 30,
            discount: 28,
          },
          {
            id: 5,
            name: "Spatula",
            price: "8458.51",
            rate: "3280.13",
            kg: null,
            pcs: 22,
            discount: 12,
          },
        ],
      },
      {
        date: "2022/6/18",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "9663.51",
            rate: "4558.72",
            kg: null,
            pcs: 21,
            discount: 18,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "9341.30",
            rate: "1507.20",
            kg: null,
            pcs: 20,
            discount: 28,
          },
        ],
      },
      {
        date: "2023/12/12",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "8177.80",
            rate: "1774.96",
            kg: null,
            pcs: 13,
            discount: 20,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "5653.27",
            rate: "3684.06",
            kg: "5.76",
            pcs: 23,
            discount: 27,
          },
          {
            id: 3,
            name: "Blender",
            price: "6356.59",
            rate: "1345.16",
            kg: null,
            pcs: 10,
            discount: 22,
          },
          {
            id: 4,
            name: "Spatula",
            price: "9968.42",
            rate: "3959.47",
            kg: "4.92",
            pcs: 5,
            discount: 16,
          },
          {
            id: 5,
            name: "Knife",
            price: "6059.63",
            rate: "4387.65",
            kg: "3.15",
            pcs: 19,
            discount: 24,
          },
        ],
      },
      {
        date: "2023/4/26",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "8477.64",
            rate: "2494.35",
            kg: null,
            pcs: 19,
            discount: 17,
          },
          {
            id: 2,
            name: "Whisk",
            price: "9313.25",
            rate: "2338.63",
            kg: null,
            pcs: 26,
            discount: 22,
          },
        ],
      },
      {
        date: "2020/1/14",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "5676.59",
            rate: "4212.70",
            kg: null,
            pcs: 29,
            discount: 21,
          },
          {
            id: 2,
            name: "Knife",
            price: "5297.02",
            rate: "3138.37",
            kg: null,
            pcs: 22,
            discount: 24,
          },
        ],
      },
      {
        date: "2021/11/28",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "6238.99",
            rate: "2842.82",
            kg: null,
            pcs: 3,
            discount: 14,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "6766.71",
            rate: "3764.83",
            kg: "1.72",
            pcs: 28,
            discount: 21,
          },
          {
            id: 3,
            name: "Blender",
            price: "9026.18",
            rate: "1474.02",
            kg: null,
            pcs: 15,
            discount: 22,
          },
          {
            id: 4,
            name: "Whisk",
            price: "8419.23",
            rate: "4322.67",
            kg: "0.70",
            pcs: 25,
            discount: 26,
          },
        ],
      },
      {
        date: "2023/2/10",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "9225.17",
            rate: "1336.11",
            kg: "1.15",
            pcs: 22,
            discount: 25,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "8176.41",
            rate: "1934.43",
            kg: null,
            pcs: 15,
            discount: 20,
          },
          {
            id: 3,
            name: "Colander",
            price: "8866.84",
            rate: "2926.61",
            kg: "1.51",
            pcs: 26,
            discount: 21,
          },
        ],
      },
      {
        date: "2020/12/25",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "8677.70",
            rate: "4399.05",
            kg: null,
            pcs: 28,
            discount: 29,
          },
          {
            id: 2,
            name: "Colander",
            price: "9030.80",
            rate: "3974.85",
            kg: null,
            pcs: 19,
            discount: 28,
          },
          {
            id: 3,
            name: "Colander",
            price: "6238.26",
            rate: "2056.25",
            kg: null,
            pcs: 29,
            discount: 17,
          },
          {
            id: 4,
            name: "Cutting Board",
            price: "6289.66",
            rate: "3091.15",
            kg: null,
            pcs: 20,
            discount: 10,
          },
        ],
      },
      {
        date: "2020/9/18",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "9426.72",
            rate: "2977.19",
            kg: null,
            pcs: 26,
            discount: 29,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "9132.34",
            rate: "2617.24",
            kg: null,
            pcs: 19,
            discount: 30,
          },
          {
            id: 3,
            name: "Whisk",
            price: "9014.83",
            rate: "4601.68",
            kg: null,
            pcs: 25,
            discount: 16,
          },
        ],
      },
      {
        date: "2022/4/2",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "5374.83",
            rate: "2775.90",
            kg: null,
            pcs: 1,
            discount: 11,
          },
        ],
      },
      {
        date: "2022/12/1",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "9252.01",
            rate: "1544.23",
            kg: null,
            pcs: 23,
            discount: 29,
          },
          {
            id: 2,
            name: "Colander",
            price: "7585.37",
            rate: "3436.55",
            kg: null,
            pcs: 30,
            discount: 16,
          },
          {
            id: 3,
            name: "Frying Pan",
            price: "5570.49",
            rate: "2884.20",
            kg: null,
            pcs: 16,
            discount: 10,
          },
          {
            id: 4,
            name: "Blender",
            price: "6081.46",
            rate: "4740.39",
            kg: "4.20",
            pcs: 15,
            discount: 23,
          },
        ],
      },
      {
        date: "2023/8/17",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "9279.31",
            rate: "3320.92",
            kg: null,
            pcs: 1,
            discount: 26,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "6066.04",
            rate: "2962.78",
            kg: null,
            pcs: 6,
            discount: 17,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "5734.48",
            rate: "2789.11",
            kg: "4.59",
            pcs: 14,
            discount: 28,
          },
          {
            id: 4,
            name: "Mixing Bowl",
            price: "5603.73",
            rate: "3983.00",
            kg: "9.91",
            pcs: 22,
            discount: 20,
          },
          {
            id: 5,
            name: "Mixing Bowl",
            price: "5151.20",
            rate: "1822.20",
            kg: "9.34",
            pcs: 24,
            discount: 25,
          },
        ],
      },
      {
        date: "2023/6/6",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "5316.77",
            rate: "1655.58",
            kg: "8.47",
            pcs: 12,
            discount: 22,
          },
        ],
      },
      {
        date: "2021/4/2",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "7272.20",
            rate: "3807.70",
            kg: null,
            pcs: 18,
            discount: 25,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "9890.25",
            rate: "4704.74",
            kg: null,
            pcs: 1,
            discount: 15,
          },
          {
            id: 3,
            name: "Peeler",
            price: "5148.03",
            rate: "4941.24",
            kg: null,
            pcs: 26,
            discount: 17,
          },
        ],
      },
      {
        date: "2022/8/14",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "8119.66",
            rate: "2255.93",
            kg: null,
            pcs: 26,
            discount: 18,
          },
          {
            id: 2,
            name: "Spatula",
            price: "6564.55",
            rate: "2877.85",
            kg: null,
            pcs: 10,
            discount: 14,
          },
          {
            id: 3,
            name: "Measuring Cup",
            price: "7823.08",
            rate: "1179.91",
            kg: null,
            pcs: 3,
            discount: 15,
          },
          {
            id: 4,
            name: "Spatula",
            price: "8209.33",
            rate: "4282.25",
            kg: null,
            pcs: 16,
            discount: 15,
          },
          {
            id: 5,
            name: "Measuring Cup",
            price: "7732.44",
            rate: "3564.41",
            kg: "7.09",
            pcs: 28,
            discount: 12,
          },
        ],
      },
      {
        date: "2020/10/24",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "9092.23",
            rate: "4992.87",
            kg: null,
            pcs: 20,
            discount: 20,
          },
          {
            id: 2,
            name: "Blender",
            price: "5606.62",
            rate: "2744.26",
            kg: "4.81",
            pcs: 30,
            discount: 16,
          },
        ],
      },
      {
        date: "2020/8/31",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "5753.84",
            rate: "2797.19",
            kg: "3.48",
            pcs: 26,
            discount: 24,
          },
        ],
      },
      {
        date: "2021/8/25",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "6120.37",
            rate: "2006.11",
            kg: "6.83",
            pcs: 20,
            discount: 25,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "8541.11",
            rate: "2375.73",
            kg: "3.94",
            pcs: 3,
            discount: 10,
          },
        ],
      },
      {
        date: "2023/7/15",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "6530.24",
            rate: "2131.43",
            kg: null,
            pcs: 25,
            discount: 18,
          },
          {
            id: 2,
            name: "Knife",
            price: "9652.56",
            rate: "4031.13",
            kg: "0.72",
            pcs: 18,
            discount: 24,
          },
          {
            id: 3,
            name: "Colander",
            price: "7261.83",
            rate: "4539.62",
            kg: null,
            pcs: 9,
            discount: 23,
          },
        ],
      },
      {
        date: "2023/4/1",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "5970.39",
            rate: "4934.84",
            kg: "5.35",
            pcs: 7,
            discount: 30,
          },
          {
            id: 2,
            name: "Colander",
            price: "5474.96",
            rate: "1137.03",
            kg: "8.50",
            pcs: 6,
            discount: 23,
          },
          {
            id: 3,
            name: "Cutting Board",
            price: "5333.28",
            rate: "3721.66",
            kg: null,
            pcs: 1,
            discount: 24,
          },
        ],
      },
      {
        date: "2020/2/2",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "5965.81",
            rate: "3076.12",
            kg: "5.32",
            pcs: 30,
            discount: 20,
          },
          {
            id: 2,
            name: "Spatula",
            price: "9659.49",
            rate: "4580.64",
            kg: "8.49",
            pcs: 13,
            discount: 15,
          },
          {
            id: 3,
            name: "Colander",
            price: "6917.26",
            rate: "1176.64",
            kg: null,
            pcs: 9,
            discount: 14,
          },
          {
            id: 4,
            name: "Cutting Board",
            price: "5907.28",
            rate: "4357.41",
            kg: null,
            pcs: 20,
            discount: 22,
          },
          {
            id: 5,
            name: "Whisk",
            price: "5790.20",
            rate: "2118.32",
            kg: null,
            pcs: 14,
            discount: 10,
          },
        ],
      },
      {
        date: "2021/10/28",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "7493.59",
            rate: "4203.77",
            kg: null,
            pcs: 24,
            discount: 15,
          },
        ],
      },
      {
        date: "2023/4/8",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "9951.03",
            rate: "3095.05",
            kg: "9.96",
            pcs: 20,
            discount: 21,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "9400.78",
            rate: "1203.77",
            kg: "8.71",
            pcs: 15,
            discount: 15,
          },
          {
            id: 3,
            name: "Peeler",
            price: "7880.24",
            rate: "3734.25",
            kg: null,
            pcs: 29,
            discount: 18,
          },
        ],
      },
      {
        date: "2021/2/1",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "7079.77",
            rate: "1666.48",
            kg: "2.10",
            pcs: 29,
            discount: 13,
          },
          {
            id: 2,
            name: "Blender",
            price: "7599.48",
            rate: "1658.82",
            kg: "2.88",
            pcs: 9,
            discount: 23,
          },
          {
            id: 3,
            name: "Knife",
            price: "8915.44",
            rate: "1523.21",
            kg: null,
            pcs: 22,
            discount: 19,
          },
          {
            id: 4,
            name: "Spatula",
            price: "6459.76",
            rate: "1763.08",
            kg: null,
            pcs: 3,
            discount: 13,
          },
        ],
      },
      {
        date: "2023/3/15",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "6656.19",
            rate: "1081.40",
            kg: "6.06",
            pcs: 10,
            discount: 26,
          },
        ],
      },
      {
        date: "2023/3/3",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "6951.31",
            rate: "2918.04",
            kg: null,
            pcs: 18,
            discount: 18,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "9154.64",
            rate: "4146.69",
            kg: null,
            pcs: 23,
            discount: 24,
          },
          {
            id: 3,
            name: "Cutting Board",
            price: "8237.97",
            rate: "1308.62",
            kg: null,
            pcs: 8,
            discount: 19,
          },
          {
            id: 4,
            name: "Blender",
            price: "6292.20",
            rate: "2954.30",
            kg: "6.67",
            pcs: 3,
            discount: 14,
          },
        ],
      },
      {
        date: "2023/2/27",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "6231.95",
            rate: "1401.78",
            kg: "2.37",
            pcs: 22,
            discount: 25,
          },
          {
            id: 2,
            name: "Colander",
            price: "8550.16",
            rate: "1950.38",
            kg: "3.17",
            pcs: 26,
            discount: 22,
          },
        ],
      },
      {
        date: "2021/10/21",
        bill: [
          {
            id: 1,
            name: "Whisk",
            price: "8563.00",
            rate: "2667.32",
            kg: "7.24",
            pcs: 12,
            discount: 17,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "7508.46",
            rate: "1284.84",
            kg: "6.12",
            pcs: 28,
            discount: 18,
          },
          {
            id: 3,
            name: "Knife",
            price: "8972.41",
            rate: "1014.64",
            kg: null,
            pcs: 3,
            discount: 21,
          },
          {
            id: 4,
            name: "Measuring Cup",
            price: "6911.88",
            rate: "4510.84",
            kg: null,
            pcs: 5,
            discount: 23,
          },
        ],
      },
      {
        date: "2022/5/21",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "9305.80",
            rate: "3276.10",
            kg: "9.16",
            pcs: 13,
            discount: 13,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "9847.42",
            rate: "3301.23",
            kg: "4.11",
            pcs: 4,
            discount: 15,
          },
        ],
      },
      {
        date: "2023/11/2",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "6786.90",
            rate: "1063.13",
            kg: "5.05",
            pcs: 19,
            discount: 22,
          },
        ],
      },
      {
        date: "2021/7/6",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "8358.41",
            rate: "2842.89",
            kg: null,
            pcs: 24,
            discount: 18,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "8247.86",
            rate: "1302.54",
            kg: "7.34",
            pcs: 27,
            discount: 17,
          },
        ],
      },
      {
        date: "2020/12/4",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "5819.79",
            rate: "3841.83",
            kg: "1.84",
            pcs: 9,
            discount: 23,
          },
        ],
      },
      {
        date: "2021/4/25",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "5136.07",
            rate: "1815.29",
            kg: null,
            pcs: 14,
            discount: 15,
          },
          {
            id: 2,
            name: "Cutting Board",
            price: "6557.20",
            rate: "1535.94",
            kg: "5.32",
            pcs: 9,
            discount: 17,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "6312.92",
            rate: "2420.91",
            kg: "8.55",
            pcs: 29,
            discount: 10,
          },
          {
            id: 4,
            name: "Whisk",
            price: "9510.89",
            rate: "2278.82",
            kg: "7.11",
            pcs: 18,
            discount: 16,
          },
          {
            id: 5,
            name: "Mixing Bowl",
            price: "5588.45",
            rate: "1427.69",
            kg: "1.58",
            pcs: 27,
            discount: 17,
          },
        ],
      },
      {
        date: "2020/6/9",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "8801.10",
            rate: "2274.94",
            kg: "6.45",
            pcs: 2,
            discount: 15,
          },
          {
            id: 2,
            name: "Colander",
            price: "7048.14",
            rate: "1683.03",
            kg: "2.17",
            pcs: 23,
            discount: 23,
          },
          {
            id: 3,
            name: "Colander",
            price: "6648.36",
            rate: "1358.43",
            kg: null,
            pcs: 18,
            discount: 16,
          },
          {
            id: 4,
            name: "Measuring Cup",
            price: "9112.41",
            rate: "2800.11",
            kg: "2.49",
            pcs: 17,
            discount: 22,
          },
          {
            id: 5,
            name: "Measuring Cup",
            price: "9151.35",
            rate: "4557.51",
            kg: "7.05",
            pcs: 24,
            discount: 15,
          },
        ],
      },
      {
        date: "2020/3/13",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "6012.91",
            rate: "2420.25",
            kg: null,
            pcs: 19,
            discount: 18,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "6644.08",
            rate: "2319.04",
            kg: "6.73",
            pcs: 26,
            discount: 28,
          },
          {
            id: 3,
            name: "Measuring Cup",
            price: "7689.30",
            rate: "3866.64",
            kg: "5.29",
            pcs: 29,
            discount: 20,
          },
          {
            id: 4,
            name: "Cutting Board",
            price: "9561.26",
            rate: "3785.74",
            kg: null,
            pcs: 5,
            discount: 16,
          },
          {
            id: 5,
            name: "Blender",
            price: "6034.49",
            rate: "4769.77",
            kg: null,
            pcs: 5,
            discount: 17,
          },
        ],
      },
      {
        date: "2022/12/15",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "9671.04",
            rate: "1372.28",
            kg: null,
            pcs: 29,
            discount: 17,
          },
          {
            id: 2,
            name: "Knife",
            price: "9558.01",
            rate: "3400.73",
            kg: "4.23",
            pcs: 28,
            discount: 15,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "8290.96",
            rate: "3657.57",
            kg: null,
            pcs: 28,
            discount: 18,
          },
          {
            id: 4,
            name: "Spatula",
            price: "9992.13",
            rate: "4330.20",
            kg: null,
            pcs: 27,
            discount: 25,
          },
          {
            id: 5,
            name: "Knife",
            price: "7623.62",
            rate: "4054.80",
            kg: null,
            pcs: 15,
            discount: 15,
          },
        ],
      },
      {
        date: "2023/3/5",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "6013.62",
            rate: "2234.95",
            kg: null,
            pcs: 6,
            discount: 12,
          },
        ],
      },
      {
        date: "2020/1/3",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "6453.34",
            rate: "4052.26",
            kg: null,
            pcs: 18,
            discount: 16,
          },
          {
            id: 2,
            name: "Whisk",
            price: "5198.60",
            rate: "4673.67",
            kg: "6.17",
            pcs: 18,
            discount: 10,
          },
        ],
      },
      {
        date: "2023/9/27",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "8523.69",
            rate: "3653.80",
            kg: "4.74",
            pcs: 23,
            discount: 12,
          },
          {
            id: 2,
            name: "Blender",
            price: "9530.95",
            rate: "4502.09",
            kg: null,
            pcs: 7,
            discount: 28,
          },
          {
            id: 3,
            name: "Whisk",
            price: "7255.77",
            rate: "1352.15",
            kg: null,
            pcs: 12,
            discount: 28,
          },
          {
            id: 4,
            name: "Colander",
            price: "7660.19",
            rate: "1333.90",
            kg: null,
            pcs: 30,
            discount: 18,
          },
          {
            id: 5,
            name: "Knife",
            price: "6944.61",
            rate: "4974.78",
            kg: null,
            pcs: 25,
            discount: 12,
          },
        ],
      },
      {
        date: "2023/6/3",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "9770.40",
            rate: "1326.69",
            kg: null,
            pcs: 16,
            discount: 24,
          },
        ],
      },
      {
        date: "2021/3/31",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "9766.00",
            rate: "1097.29",
            kg: "2.76",
            pcs: 22,
            discount: 11,
          },
          {
            id: 2,
            name: "Colander",
            price: "7894.40",
            rate: "3431.16",
            kg: null,
            pcs: 3,
            discount: 26,
          },
          {
            id: 3,
            name: "Spatula",
            price: "6721.11",
            rate: "4850.12",
            kg: null,
            pcs: 18,
            discount: 25,
          },
        ],
      },
      {
        date: "2020/2/8",
        bill: [
          {
            id: 1,
            name: "Whisk",
            price: "5704.81",
            rate: "2136.68",
            kg: null,
            pcs: 3,
            discount: 23,
          },
          {
            id: 2,
            name: "Spatula",
            price: "6473.25",
            rate: "1900.17",
            kg: "4.62",
            pcs: 5,
            discount: 22,
          },
        ],
      },
      {
        date: "2022/2/22",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "6491.18",
            rate: "4365.70",
            kg: "6.77",
            pcs: 9,
            discount: 16,
          },
        ],
      },
      {
        date: "2023/8/12",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "8096.57",
            rate: "2775.51",
            kg: "9.30",
            pcs: 28,
            discount: 25,
          },
        ],
      },
      {
        date: "2023/3/19",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "5566.87",
            rate: "2095.57",
            kg: null,
            pcs: 5,
            discount: 14,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "8700.51",
            rate: "3313.13",
            kg: null,
            pcs: 1,
            discount: 26,
          },
        ],
      },
      {
        date: "2022/3/17",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "8722.03",
            rate: "1835.77",
            kg: "1.15",
            pcs: 29,
            discount: 10,
          },
          {
            id: 2,
            name: "Knife",
            price: "5293.56",
            rate: "2376.68",
            kg: null,
            pcs: 27,
            discount: 25,
          },
        ],
      },
      {
        date: "2020/3/28",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "7376.42",
            rate: "2249.63",
            kg: "9.95",
            pcs: 26,
            discount: 11,
          },
        ],
      },
      {
        date: "2020/3/27",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "5676.41",
            rate: "2050.98",
            kg: null,
            pcs: 27,
            discount: 13,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "7323.03",
            rate: "1620.46",
            kg: "1.55",
            pcs: 1,
            discount: 16,
          },
          {
            id: 3,
            name: "Frying Pan",
            price: "6223.03",
            rate: "2431.01",
            kg: "8.48",
            pcs: 16,
            discount: 28,
          },
          {
            id: 4,
            name: "Cutting Board",
            price: "7597.44",
            rate: "1278.47",
            kg: "5.64",
            pcs: 2,
            discount: 28,
          },
        ],
      },
      {
        date: "2023/9/16",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "9854.15",
            rate: "3335.81",
            kg: null,
            pcs: 14,
            discount: 10,
          },
          {
            id: 2,
            name: "Knife",
            price: "7000.79",
            rate: "4323.29",
            kg: "3.25",
            pcs: 2,
            discount: 14,
          },
        ],
      },
      {
        date: "2023/5/7",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "8586.64",
            rate: "4232.57",
            kg: null,
            pcs: 28,
            discount: 14,
          },
          {
            id: 2,
            name: "Blender",
            price: "7069.20",
            rate: "2207.37",
            kg: "3.13",
            pcs: 20,
            discount: 21,
          },
          {
            id: 3,
            name: "Knife",
            price: "6009.55",
            rate: "1726.35",
            kg: "8.65",
            pcs: 30,
            discount: 15,
          },
          {
            id: 4,
            name: "Whisk",
            price: "8685.96",
            rate: "4653.22",
            kg: "9.79",
            pcs: 1,
            discount: 23,
          },
          {
            id: 5,
            name: "Frying Pan",
            price: "7543.71",
            rate: "3914.34",
            kg: null,
            pcs: 20,
            discount: 11,
          },
        ],
      },
      {
        date: "2021/12/9",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "6057.05",
            rate: "1062.78",
            kg: "3.56",
            pcs: 13,
            discount: 20,
          },
        ],
      },
      {
        date: "2022/1/2",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "9099.45",
            rate: "2114.97",
            kg: "8.63",
            pcs: 14,
            discount: 30,
          },
          {
            id: 2,
            name: "Blender",
            price: "7350.59",
            rate: "4466.46",
            kg: "5.32",
            pcs: 1,
            discount: 25,
          },
        ],
      },
      {
        date: "2022/11/16",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "8770.51",
            rate: "3450.11",
            kg: null,
            pcs: 10,
            discount: 14,
          },
          {
            id: 2,
            name: "Knife",
            price: "6285.53",
            rate: "4256.72",
            kg: null,
            pcs: 29,
            discount: 17,
          },
        ],
      },
      {
        date: "2023/9/2",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "8551.79",
            rate: "3428.01",
            kg: "0.76",
            pcs: 12,
            discount: 23,
          },
        ],
      },
      {
        date: "2022/2/10",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "8914.89",
            rate: "1549.75",
            kg: "8.87",
            pcs: 19,
            discount: 21,
          },
          {
            id: 2,
            name: "Peeler",
            price: "5495.89",
            rate: "4666.89",
            kg: "9.47",
            pcs: 17,
            discount: 28,
          },
        ],
      },
      {
        date: "2022/12/2",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "6597.83",
            rate: "4148.80",
            kg: null,
            pcs: 26,
            discount: 19,
          },
          {
            id: 2,
            name: "Knife",
            price: "6258.03",
            rate: "3658.33",
            kg: "1.05",
            pcs: 7,
            discount: 18,
          },
          {
            id: 3,
            name: "Measuring Cup",
            price: "7532.13",
            rate: "1862.46",
            kg: null,
            pcs: 22,
            discount: 17,
          },
          {
            id: 4,
            name: "Frying Pan",
            price: "9607.06",
            rate: "4048.48",
            kg: "4.91",
            pcs: 18,
            discount: 30,
          },
          {
            id: 5,
            name: "Frying Pan",
            price: "9773.44",
            rate: "4589.54",
            kg: "7.96",
            pcs: 29,
            discount: 11,
          },
        ],
      },
      {
        date: "2022/6/17",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "7381.94",
            rate: "4860.92",
            kg: "7.48",
            pcs: 19,
            discount: 10,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "8070.53",
            rate: "4933.07",
            kg: null,
            pcs: 23,
            discount: 24,
          },
          {
            id: 3,
            name: "Frying Pan",
            price: "9575.19",
            rate: "1303.83",
            kg: "9.04",
            pcs: 5,
            discount: 16,
          },
        ],
      },
      {
        date: "2022/8/15",
        bill: [
          {
            id: 1,
            name: "Mixing Bowl",
            price: "8700.27",
            rate: "3164.11",
            kg: "4.48",
            pcs: 11,
            discount: 14,
          },
          {
            id: 2,
            name: "Knife",
            price: "7890.31",
            rate: "2261.24",
            kg: null,
            pcs: 19,
            discount: 14,
          },
          {
            id: 3,
            name: "Knife",
            price: "9409.42",
            rate: "1208.72",
            kg: "2.95",
            pcs: 13,
            discount: 30,
          },
          {
            id: 4,
            name: "Blender",
            price: "6845.32",
            rate: "4106.47",
            kg: null,
            pcs: 19,
            discount: 30,
          },
        ],
      },
      {
        date: "2023/5/13",
        bill: [
          {
            id: 1,
            name: "Blender",
            price: "8202.98",
            rate: "4614.72",
            kg: "4.95",
            pcs: 11,
            discount: 21,
          },
          {
            id: 2,
            name: "Whisk",
            price: "7178.31",
            rate: "2799.36",
            kg: "4.50",
            pcs: 17,
            discount: 10,
          },
          {
            id: 3,
            name: "Whisk",
            price: "5018.29",
            rate: "1860.03",
            kg: "6.18",
            pcs: 5,
            discount: 28,
          },
          {
            id: 4,
            name: "Whisk",
            price: "8603.06",
            rate: "4705.90",
            kg: null,
            pcs: 7,
            discount: 23,
          },
        ],
      },
      {
        date: "2020/10/20",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "9466.62",
            rate: "2482.41",
            kg: "7.57",
            pcs: 2,
            discount: 24,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "7370.62",
            rate: "4499.59",
            kg: "6.14",
            pcs: 20,
            discount: 30,
          },
          {
            id: 3,
            name: "Peeler",
            price: "8929.27",
            rate: "3408.84",
            kg: "0.70",
            pcs: 18,
            discount: 25,
          },
          {
            id: 4,
            name: "Knife",
            price: "8416.36",
            rate: "2838.87",
            kg: null,
            pcs: 7,
            discount: 20,
          },
          {
            id: 5,
            name: "Cutting Board",
            price: "8638.40",
            rate: "2847.96",
            kg: null,
            pcs: 28,
            discount: 17,
          },
        ],
      },
      {
        date: "2022/3/1",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "8756.16",
            rate: "1636.14",
            kg: "2.37",
            pcs: 2,
            discount: 13,
          },
          {
            id: 2,
            name: "Knife",
            price: "7184.00",
            rate: "2492.15",
            kg: null,
            pcs: 16,
            discount: 10,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "7025.39",
            rate: "1599.47",
            kg: null,
            pcs: 16,
            discount: 30,
          },
          {
            id: 4,
            name: "Mixing Bowl",
            price: "7952.77",
            rate: "1224.63",
            kg: "2.79",
            pcs: 6,
            discount: 24,
          },
        ],
      },
      {
        date: "2022/4/24",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "5805.66",
            rate: "1638.32",
            kg: null,
            pcs: 9,
            discount: 15,
          },
          {
            id: 2,
            name: "Measuring Cup",
            price: "7700.05",
            rate: "2857.30",
            kg: "6.59",
            pcs: 4,
            discount: 17,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "6962.19",
            rate: "4145.30",
            kg: "9.45",
            pcs: 12,
            discount: 16,
          },
        ],
      },
      {
        date: "2021/7/2",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "6891.17",
            rate: "1145.78",
            kg: "9.92",
            pcs: 16,
            discount: 10,
          },
        ],
      },
      {
        date: "2022/5/27",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "9966.89",
            rate: "2173.23",
            kg: "7.78",
            pcs: 27,
            discount: 18,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "7276.59",
            rate: "4396.55",
            kg: null,
            pcs: 28,
            discount: 13,
          },
          {
            id: 3,
            name: "Knife",
            price: "5097.27",
            rate: "2697.15",
            kg: null,
            pcs: 13,
            discount: 16,
          },
          {
            id: 4,
            name: "Mixing Bowl",
            price: "6879.27",
            rate: "1267.50",
            kg: "1.55",
            pcs: 17,
            discount: 24,
          },
          {
            id: 5,
            name: "Spatula",
            price: "5953.01",
            rate: "3375.37",
            kg: null,
            pcs: 6,
            discount: 29,
          },
        ],
      },
      {
        date: "2020/10/15",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "8572.66",
            rate: "4314.38",
            kg: "4.15",
            pcs: 26,
            discount: 30,
          },
          {
            id: 2,
            name: "Knife",
            price: "8057.42",
            rate: "2798.76",
            kg: null,
            pcs: 9,
            discount: 25,
          },
          {
            id: 3,
            name: "Blender",
            price: "6376.62",
            rate: "2802.22",
            kg: null,
            pcs: 16,
            discount: 23,
          },
        ],
      },
      {
        date: "2021/6/21",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "8148.67",
            rate: "2931.10",
            kg: "9.00",
            pcs: 19,
            discount: 17,
          },
          {
            id: 2,
            name: "Knife",
            price: "7060.77",
            rate: "4037.40",
            kg: "2.02",
            pcs: 2,
            discount: 29,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "9612.51",
            rate: "4021.56",
            kg: null,
            pcs: 8,
            discount: 25,
          },
          {
            id: 4,
            name: "Knife",
            price: "7482.81",
            rate: "1596.64",
            kg: null,
            pcs: 21,
            discount: 13,
          },
          {
            id: 5,
            name: "Measuring Cup",
            price: "8187.84",
            rate: "4709.28",
            kg: "2.80",
            pcs: 18,
            discount: 14,
          },
        ],
      },
      {
        date: "2023/10/11",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "8743.39",
            rate: "1499.48",
            kg: "9.07",
            pcs: 26,
            discount: 17,
          },
        ],
      },
      {
        date: "2020/3/31",
        bill: [
          {
            id: 1,
            name: "Colander",
            price: "8919.56",
            rate: "4889.96",
            kg: "1.12",
            pcs: 5,
            discount: 13,
          },
          {
            id: 2,
            name: "Knife",
            price: "9922.80",
            rate: "4395.12",
            kg: "9.52",
            pcs: 24,
            discount: 23,
          },
          {
            id: 3,
            name: "Cutting Board",
            price: "5829.71",
            rate: "2151.85",
            kg: "3.94",
            pcs: 26,
            discount: 29,
          },
          {
            id: 4,
            name: "Spatula",
            price: "8487.72",
            rate: "2926.34",
            kg: "2.05",
            pcs: 15,
            discount: 30,
          },
          {
            id: 5,
            name: "Peeler",
            price: "7725.15",
            rate: "1195.32",
            kg: null,
            pcs: 28,
            discount: 26,
          },
        ],
      },
      {
        date: "2022/1/1",
        bill: [
          {
            id: 1,
            name: "Peeler",
            price: "5887.83",
            rate: "4465.62",
            kg: null,
            pcs: 1,
            discount: 30,
          },
          {
            id: 2,
            name: "Frying Pan",
            price: "9531.24",
            rate: "2525.72",
            kg: null,
            pcs: 30,
            discount: 13,
          },
          {
            id: 3,
            name: "Cutting Board",
            price: "5796.02",
            rate: "1215.30",
            kg: null,
            pcs: 9,
            discount: 29,
          },
          {
            id: 4,
            name: "Measuring Cup",
            price: "5789.68",
            rate: "4776.30",
            kg: null,
            pcs: 15,
            discount: 11,
          },
          {
            id: 5,
            name: "Spatula",
            price: "5472.29",
            rate: "3673.78",
            kg: null,
            pcs: 10,
            discount: 16,
          },
        ],
      },
      {
        date: "2021/8/3",
        bill: [
          {
            id: 1,
            name: "Frying Pan",
            price: "8666.73",
            rate: "4260.74",
            kg: "8.20",
            pcs: 19,
            discount: 14,
          },
          {
            id: 2,
            name: "Knife",
            price: "6136.60",
            rate: "3095.31",
            kg: "1.76",
            pcs: 25,
            discount: 17,
          },
          {
            id: 3,
            name: "Knife",
            price: "7561.42",
            rate: "3334.36",
            kg: null,
            pcs: 11,
            discount: 30,
          },
          {
            id: 4,
            name: "Measuring Cup",
            price: "5391.96",
            rate: "4172.56",
            kg: "6.17",
            pcs: 5,
            discount: 21,
          },
        ],
      },
      {
        date: "2022/3/28",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "8995.38",
            rate: "3017.75",
            kg: "5.48",
            pcs: 14,
            discount: 10,
          },
          {
            id: 2,
            name: "Whisk",
            price: "8467.15",
            rate: "2015.16",
            kg: "3.58",
            pcs: 26,
            discount: 28,
          },
        ],
      },
      {
        date: "2021/6/20",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "9363.71",
            rate: "2217.71",
            kg: "7.56",
            pcs: 16,
            discount: 20,
          },
          {
            id: 2,
            name: "Knife",
            price: "5527.49",
            rate: "1657.97",
            kg: "3.88",
            pcs: 4,
            discount: 24,
          },
          {
            id: 3,
            name: "Frying Pan",
            price: "6937.86",
            rate: "4789.28",
            kg: "2.58",
            pcs: 9,
            discount: 14,
          },
        ],
      },
      {
        date: "2022/11/15",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            price: "9617.25",
            rate: "4226.29",
            kg: null,
            pcs: 17,
            discount: 28,
          },
          {
            id: 2,
            name: "Mixing Bowl",
            price: "5677.84",
            rate: "4412.80",
            kg: "2.02",
            pcs: 10,
            discount: 30,
          },
          {
            id: 3,
            name: "Peeler",
            price: "6342.36",
            rate: "1643.48",
            kg: "8.37",
            pcs: 10,
            discount: 16,
          },
          {
            id: 4,
            name: "Frying Pan",
            price: "5815.08",
            rate: "3688.48",
            kg: "6.64",
            pcs: 7,
            discount: 23,
          },
          {
            id: 5,
            name: "Knife",
            price: "7949.07",
            rate: "3754.43",
            kg: "5.44",
            pcs: 15,
            discount: 30,
          },
        ],
      },
      {
        date: "2022/11/8",
        bill: [
          {
            id: 1,
            name: "Spatula",
            price: "9699.24",
            rate: "4075.79",
            kg: null,
            pcs: 26,
            discount: 17,
          },
          {
            id: 2,
            name: "Whisk",
            price: "8446.91",
            rate: "3244.12",
            kg: null,
            pcs: 17,
            discount: 26,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            price: "5236.11",
            rate: "1504.57",
            kg: "7.10",
            pcs: 13,
            discount: 13,
          },
        ],
      },
      {
        date: "2021/4/15",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            price: "8279.12",
            rate: "4334.17",
            kg: null,
            pcs: 14,
            discount: 17,
          },
        ],
      },
      {
        date: "2021/4/6",
        bill: [
          {
            id: 1,
            name: "Knife",
            price: "9878.21",
            rate: "2272.12",
            kg: null,
            pcs: 7,
            discount: 17,
          },
          {
            id: 2,
            name: "Cutting Board",
            price: "5713.43",
            rate: "2533.67",
            kg: null,
            pcs: 5,
            discount: 11,
          },
          {
            id: 3,
            name: "Colander",
            price: "5188.54",
            rate: "3413.95",
            kg: "5.89",
            pcs: 24,
            discount: 20,
          },
          {
            id: 4,
            name: "Blender",
            price: "8036.21",
            rate: "1440.60",
            kg: "5.93",
            pcs: 2,
            discount: 14,
          },
          {
            id: 5,
            name: "Knife",
            price: "7430.40",
            rate: "4121.68",
            kg: "5.28",
            pcs: 24,
            discount: 11,
          },
        ],
      },
    ],
    salesBillData: [
      {
        date: "2023/3/18",
        bill: [
          {
            id: 1,
            name: "Colander",
            salesRate: "7042.02",
            profit: "3407.36",
            pcs: 13,
          },
          {
            id: 2,
            name: "Colander",
            salesRate: "6348.65",
            profit: "3798.38",
            pcs: 21,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            salesRate: "8079.62",
            profit: "4421.04",
            pcs: 7,
          },
          {
            id: 4,
            name: "Blender",
            salesRate: "7496.12",
            profit: "2767.89",
            pcs: 27,
          },
          {
            id: 5,
            name: "Measuring Cup",
            salesRate: "7873.59",
            profit: "1873.99",
            pcs: 8,
          },
        ],
      },
      {
        date: "2023/2/13",
        bill: [
          {
            id: 1,
            name: "Colander",
            salesRate: "5531.48",
            profit: "2847.97",
            pcs: 8,
          },
          {
            id: 2,
            name: "Spatula",
            salesRate: "9543.13",
            profit: "4329.14",
            pcs: 6,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            salesRate: "5019.15",
            profit: "3500.17",
            pcs: 6,
          },
        ],
      },
      {
        date: "2023/3/14",
        bill: [
          {
            id: 1,
            name: "Peeler",
            salesRate: "5790.23",
            profit: "1676.52",
            pcs: 1,
          },
          {
            id: 2,
            name: "Blender",
            salesRate: "5424.13",
            profit: "4218.06",
            pcs: 17,
          },
        ],
      },
      {
        date: "2023/3/17",
        bill: [
          {
            id: 1,
            name: "Blender",
            salesRate: "5809.26",
            profit: "1439.77",
            pcs: 18,
          },
          {
            id: 2,
            name: "Frying Pan",
            salesRate: "6376.92",
            profit: "1180.77",
            pcs: 24,
          },
          {
            id: 3,
            name: "Whisk",
            salesRate: "5859.57",
            profit: "2651.63",
            pcs: 26,
          },
          {
            id: 4,
            name: "Frying Pan",
            salesRate: "7499.39",
            profit: "1405.18",
            pcs: 3,
          },
          {
            id: 5,
            name: "Spatula",
            salesRate: "7436.21",
            profit: "3678.95",
            pcs: 18,
          },
        ],
      },
      {
        date: "2023/1/18",
        bill: [
          {
            id: 1,
            name: "Whisk",
            salesRate: "6470.06",
            profit: "3170.10",
            pcs: 12,
          },
        ],
      },
      {
        date: "2023/3/22",
        bill: [
          {
            id: 1,
            name: "Knife",
            salesRate: "9187.22",
            profit: "2479.43",
            pcs: 9,
          },
          {
            id: 2,
            name: "Blender",
            salesRate: "7517.60",
            profit: "4748.89",
            pcs: 28,
          },
          {
            id: 3,
            name: "Knife",
            salesRate: "8854.22",
            profit: "2837.74",
            pcs: 25,
          },
          {
            id: 4,
            name: "Spatula",
            salesRate: "9956.08",
            profit: "1720.82",
            pcs: 13,
          },
        ],
      },
      {
        date: "2023/2/19",
        bill: [
          {
            id: 1,
            name: "Colander",
            salesRate: "7266.54",
            profit: "3104.06",
            pcs: 2,
          },
          {
            id: 2,
            name: "Blender",
            salesRate: "6381.32",
            profit: "3167.56",
            pcs: 5,
          },
          {
            id: 3,
            name: "Colander",
            salesRate: "6702.23",
            profit: "1065.21",
            pcs: 25,
          },
          {
            id: 4,
            name: "Colander",
            salesRate: "7292.03",
            profit: "3753.92",
            pcs: 18,
          },
          {
            id: 5,
            name: "Cutting Board",
            salesRate: "5547.89",
            profit: "3980.24",
            pcs: 4,
          },
        ],
      },
      {
        date: "2023/2/2",
        bill: [
          {
            id: 1,
            name: "Cutting Board",
            salesRate: "6999.55",
            profit: "3334.56",
            pcs: 9,
          },
          {
            id: 2,
            name: "Whisk",
            salesRate: "9270.03",
            profit: "2007.69",
            pcs: 22,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            salesRate: "5907.81",
            profit: "3480.13",
            pcs: 15,
          },
        ],
      },
      {
        date: "2023/2/21",
        bill: [
          {
            id: 1,
            name: "Blender",
            salesRate: "7860.58",
            profit: "1065.13",
            pcs: 14,
          },
          {
            id: 2,
            name: "Measuring Cup",
            salesRate: "5211.12",
            profit: "3607.41",
            pcs: 6,
          },
        ],
      },
      {
        date: "2023/1/25",
        bill: [
          {
            id: 1,
            name: "Measuring Cup",
            salesRate: "6265.08",
            profit: "3825.06",
            pcs: 6,
          },
          {
            id: 2,
            name: "Blender",
            salesRate: "8781.51",
            profit: "4161.52",
            pcs: 22,
          },
          {
            id: 3,
            name: "Mixing Bowl",
            salesRate: "7446.41",
            profit: "2793.03",
            pcs: 22,
          },
        ],
      },
    ]
  };